{% set name = "spikingjelly" %}
{% set version = "0.0.0.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spikingjelly-{{ version }}.tar.gz
  sha256: c614c77ee2dcd9b074d86917a71c0cc5dd4163502b730b066ec5b5ca61727e3c

build:
  script: cp $RECIPE_DIR/fake_requirements.txt ./requirements.txt && {{ PYTHON }} -m pip install . -vv --no-deps
  number: 0
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - matplotlib-base
    - numpy
    - onnx
    - python >=3.6
    - scipy
    - pytorch >=1.5.0
    - torchvision
    - tqdm
    - cupy

test:
  imports:
    - spikingjelly
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/fangwei123456/spikingjelly
  summary: A deep learning framework for SNNs built on PyTorch.
  license: LicenseRef-NOASSERTION
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Tobias-Fischer
